
export interface StudentProject {
  id: number;
  studentId: string;
  name: string;
  project: string;
  description: string;
  websiteUrl: string;
  githubUrl: string;
  thumbnail: string;
  hasWebsite: boolean;
  hasCustomImage: boolean;
}

export const studentProjects: StudentProject[] = [
  // Students with deployed websites (prioritized)
  {
    id: 1,
    studentId: "714230001",
    name: "Viola Septianti Elsiana",
    project: "EmotiDiary",
    description: "Platform digital diary dengan analisis emosi untuk tracking mood harian",
    websiteUrl: "https://emotidiary.irc-enter.tech/",
    githubUrl: "https://github.com/violasptntels/EmotiDiary",
    thumbnail: "/images/Viola.jpeg",
    hasWebsite: true,
    hasCustomImage: true,
  },
  {
    id: 2,
    studentId: "714230027",
    name: "Muhamad Haekal Syukur",
    project: "TeamTune",
    description: "Aplikasi kolaborasi tim dengan fitur mood synchronization untuk produktivitas",
    websiteUrl: "https://teamtune.irc-enter.tech",
    githubUrl: "https://github.com/Haekalss/TeamTune",
    thumbnail: "/images/Haekal.jpg",
    hasWebsite: true,
    hasCustomImage: false,
  },
  {
    id: 3,
    studentId: "714230059",
    name: "Moch Restu Agis Burhanudin",
    project: "MoodTrack",
    description: "Sistem deteksi mood menggunakan kamera dengan teknologi computer vision",
    websiteUrl: "https://moodtrack.irc-enter.tech",
    githubUrl: "https://github.com/mrestuab/kamera_deteksi",
    thumbnail: "/images/Restu.PNG",
    hasWebsite: true,
    hasCustomImage: false,
  },
  {
    id: 4,
    studentId: "714230047",
    name: "Dina Oktafiani",
    project: "EmoTeam",
    description: "Platform sinkronisasi emosi tim untuk meningkatkan kolaborasi kerja",
    websiteUrl: "https://emoteamsync.irc-enter.tech/",
    githubUrl: "https://github.com/cinnong/EmoTeam_Sync",
    thumbnail: "/images/Dina.png",
    hasWebsite: true,
    hasCustomImage: false,
  },
  {
    id: 5,
    studentId: "714230062",
    name: "Rizqi Iqmal Fauzan",
    project: "Moodly",
    description: "Aplikasi mood tracker dengan interface yang user-friendly dan analytics",
    websiteUrl: "https://moodly.irc-enter.tech/index.html",
    githubUrl: "https://github.com/rizqiiqmal/Moodly",
    thumbnail: "/images/Iqmal.png",
    hasWebsite: true,
    hasCustomImage: false,
  },
  // Students with GitHub repositories
  {
    id: 6,
    studentId: "714230068",
    name: "Aqila Zafira",
    project: "CollabMood",
    description: "Platform kolaborasi dengan fitur mood-based team management",
    websiteUrl: "https://github.com/aqilazafira/collab_mood",
    githubUrl: "https://github.com/aqilazafira/collab_mood",
    thumbnail: "/images/Aqila.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 7,
    studentId: "714230065",
    name: "Dwi Puspa Firdaus",
    project: "Scrummood",
    description: "Aplikasi scrum management dengan integrasi mood tracking untuk tim agile",
    websiteUrl: "https://github.com/DwiFirdaus08/scrummood-fe",
    githubUrl: "https://github.com/DwiFirdaus08/scrummood-fe",
    thumbnail: "/images/Dwi.jpg",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 8,
    studentId: "714230051",
    name: "Indra Agustin",
    project: "MoodVis",
    description: "Sistem visualisasi mood dengan dashboard analytics yang komprehensif",
    websiteUrl: "https://github.com/indraagstin025/Moodvis-Mood_Visualization",
    githubUrl: "https://github.com/indraagstin025/Moodvis-Mood_Visualization",
    thumbnail: "/images/Indra.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 9,
    studentId: "714230064",
    name: "A.M. Faraziftan",
    project: "RoiyanApp",
    description: "Aplikasi mobile untuk tracking dan analisis mood dengan fitur AI",
    websiteUrl: "https://github.com/FARAZIFTAN/RoiyanApp",
    githubUrl: "https://github.com/FARAZIFTAN/RoiyanApp",
    thumbnail: "/images/Razif.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 10,
    studentId: "714230060",
    name: "Muhammad Ferdy Leoza",
    project: "TemanSuasana",
    description: "Platform social untuk berbagi dan tracking suasana hati bersama teman",
    websiteUrl: "https://github.com/ferdyleoza/TemanSuasana",
    githubUrl: "https://github.com/ferdyleoza/TemanSuasana",
    thumbnail: "/images/Ferdy.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 11,
    studentId: "714230069",
    name: "Aghni Hasna Mufida",
    project: "Well Check",
    description: "Aplikasi wellbeing check untuk monitoring kesehatan mental harian",
    websiteUrl: "https://github.com/aghniihsn/wellbeing-check.git",
    githubUrl: "https://github.com/aghniihsn/wellbeing-check.git",
    thumbnail: "/images/Aghni.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 12,
    studentId: "714230038",
    name: "Reyhan Dwiyan Nugraha",
    project: "CoEmotion",
    description: "Platform collaborative emotion sharing untuk team building",
    websiteUrl: "https://github.com/ReyhanDwiyan/NewRPL",
    githubUrl: "https://github.com/ReyhanDwiyan/NewRPL",
    thumbnail: "/images/Reyhan.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 13,
    studentId: "714230057",
    name: "Muhamad Hilmi Romadoni",
    project: "EmoSync",
    description: "Sistem sinkronisasi emosi real-time untuk komunikasi tim yang efektif",
    websiteUrl: "https://github.com/hilmibotak/EmoSync",
    githubUrl: "https://github.com/hilmibotak/EmoSync",
    thumbnail: "/images/Hilmi.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 14,
    studentId: "714230053",
    name: "Ahmad Lahay Mahendra",
    project: "Reflectify",
    description: "Platform refleksi diri dengan fitur journaling dan mood analytics",
    websiteUrl: "https://github.com/Mobius0263/Reflectify",
    githubUrl: "https://github.com/Mobius0263/Reflectify",
    thumbnail: "/images/Ahmad.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 15,
    studentId: "714230061",
    name: "Iqbal Herlambang",
    project: "CombatSense",
    description: "Aplikasi sensor emosi untuk gaming dan competitive environment",
    websiteUrl: "https://github.com/qibal/combatsense",
    githubUrl: "https://github.com/qibal/combatsense",
    thumbnail: "/images/Iqbal.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 16,
    studentId: "714230055",
    name: "Muhammad Hisyam Najwan",
    project: "Kolabempati",
    description: "Platform kolaborasi dengan empati menggunakan WebRTC dan Face API",
    websiteUrl: "https://github.com/HisyamSamAm/LiveKit-WebRTC-FaceApi",
    githubUrl: "https://github.com/HisyamSamAm/LiveKit-WebRTC-FaceApi",
    thumbnail: "/images/Hisyam.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 17,
    studentId: "714230056",
    name: "Raihan Aditya H",
    project: "Emobuddy",
    description: "Aplikasi companion untuk support emosional dan mental health",
    websiteUrl: "https://github.com/rrq-dev/RPL-II",
    githubUrl: "https://github.com/rrq-dev/RPL-II",
    thumbnail: "/images/Raihan.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  // Students without repositories (coming soon)
  {
    id: 18,
    studentId: "714230034",
    name: "Sarah Yohana",
    project: "Coming Soon",
    description: "Proyek sedang dalam tahap pengembangan",
    websiteUrl: "#",
    githubUrl: "#",
    thumbnail: "/images/Sarah.jpg",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 19,
    studentId: "714230044",
    name: "Mochammad Fadhail Fijratullah",
    project: "Coming Soon",
    description: "Proyek sedang dalam tahap pengembangan",
    websiteUrl: "#",
    githubUrl: "#",
    thumbnail: "/images/Fadhail.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 20,
    studentId: "714230070",
    name: "Muhammad Farid Al Mustofa",
    project: "Coming Soon",
    description: "Proyek sedang dalam tahap pengembangan",
    websiteUrl: "#",
    githubUrl: "#",
    thumbnail: "/images/Farid.jpg",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 21,
    studentId: "714230058",
    name: "Muhammad Okta Toriq Gunawan",
    project: "Coming Soon",
    description: "Proyek sedang dalam tahap pengembangan",
    websiteUrl: "#",
    githubUrl: "#",
    thumbnail: "/images/Octa.jpeg",
    hasWebsite: false,
    hasCustomImage: false,
  },
  {
    id: 22,
    studentId: "714230037",
    name: "Muhamad Saladin Eka Septian",
    project: "Coming Soon",
    description: "Proyek sedang dalam tahap pengembangan",
    websiteUrl: "#",
    githubUrl: "#",
    thumbnail: "/images/Eka.png",
    hasWebsite: false,
    hasCustomImage: false,
  },
];
